package cn.ztuo.bitrade.entity;
import lombok.Builder;
import lombok.Data;

import javax.persistence.*;

/**
 * 国际化扩展配置表(LOCALIZATION_EXTEND)
 * 
 * @author Zane
 * @version 1.0.0 2019-12-04
 */
@Entity
@Data
@IdClass(LocalizationExtend.LocalizationExtendKey.class)
@Table(name = "localization_extend")
public class LocalizationExtend implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 6318351678421128926L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 表名 */
    @Id
    @Column(name = "TABLE_NAME", unique = true, nullable = false, length = 32)
    private String tableName;

    /** 业务主键 */
    @Id
    @Column(name = "BUSI_KEY", unique = true, nullable = false, length = 255)
    private String busiKey;

    /** 列名 */
    @Id
    @Column(name = "COLUMN_NAME", unique = true, nullable = false, length = 32)
    private String columnName;

    /** 语种编码(ar_AE/en_US/ja_JP/ko_KR/zh_CN) */
    @Id
    @Column(name = "LOCALE", unique = true, nullable = false, length = 6)
    private String locale;

    /** 内容 */
    @Column(name = "CONTENT", nullable = true, length = 65535)
    private String content;

    /* This code was generated by TableGo tools, mark 1 end. */

    @Data
    public static class LocalizationExtendKey implements java.io.Serializable {
        /** 表名 */
        private String tableName;

        /** 业务主键 */
        private String busiKey;

        /** 列名 */
        private String columnName;

        /** 语种编码(ar_AE/en_US/ja_JP/ko_KR/zh_CN) */
        private String locale;
    }
}