package cn.ztuo.bitrade.entity;
import lombok.Data;

import javax.persistence.*;

/**
 * 用户钱包关联表
 * 
 * @author Zane
 * @version 1.0.0 2019-12-04
 */
@Entity
@Data
@IdClass(MemberWalletRelation.MemberWalletRelationKey.class)
@Table(name = "member_wallet_relation")
public class MemberWalletRelation implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 6318351678421128926L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 币种唯一标识 */
    @Id
    @Column(name = "COIN_KEY", unique = true, nullable = false, length = 255)
    private String coinKey;

    /** 地址 */
    @Id
    @Column(name = "ADDRESS", unique = true, nullable = false, length = 255)
    private String address;

    /** 用户ID */
    @Column(name = "MEMBER_ID", unique = true, nullable = false, length = 32)
    private Long memberId;

    /** 币种ID */
    @Column(name = "COIN_ID", unique = true, nullable = false, length = 6)
    private String coinId;

    /* This code was generated by TableGo tools, mark 1 end. */

    @Data
    public static class MemberWalletRelationKey implements java.io.Serializable {
        /** 币种唯一标识 */
        private String coinKey;

        /** 地址 */
        private String address;
    }
}